### ISSUE TITLE
NullPointerException on test page

### ISSUE THREAD

**Issue by nonZero** [synhershko/elasticsearch-analysis-hebrew#13]
On a fresh install of version 1.7 and ES 1.5 on arch, with dictionaries copied and set up, the following appears on [http://localhost:9200/_hebrew/check-word/בדיקה](http://localhost:9200/_hebrew/check-word/%D7%91%D7%93%D7%99%D7%A7%D7%94):

    {"error":"NullPointerException[null]","status":500}

No traceback can be found in elasticsearch logs.

English words work ok:  [http://localhost:9200/_hebrew/check-word/shalom](http://localhost:9200/_hebrew/check-word/shalom)

    {"word":"shalom","wordType":"NON_HEBREW"}

And a single א [http://localhost:9200/_hebrew/check-word/א](http://localhost:9200/_hebrew/check-word/%D7%90) returns:

    {word: "א", wordType: "UNRECOGNIZED"}

Any clue?

**Comment by synhershko** [comment]
@EgozyN can you have a look?

**Comment by EgozyN** [comment]
Could not reproduce on clean archlinux (2015.05.01) with elasticsearch 1.5-1.5.2 and version 1.7 of the plugin. Do you mind providing elasticsearch logs?

**Comment by nonZero** [comment]
When the servie starts, the following line appears in the log:

    [.....][INFO ][plugins                  ] [Mr. Wu] loaded [elasticsearch-analysis-hebrew], sites []

Other than that, no other output appears when the exception occurs.

Here is my plugins folder structure:

```text
/usr/share/elasticsearch/plugins:
total 12K
drwxr-xr-x 3 elasticsearch elasticsearch 4.0K May 19 01:58 .
drwxr-xr-x 3 elasticsearch elasticsearch 4.0K May 19 00:27 ..
drwxr-xr-x 3 elasticsearch elasticsearch 4.0K May 19 02:02 analysis-hebrew

/usr/share/elasticsearch/plugins/analysis-hebrew:
total 116K
drwxr-xr-x 3 elasticsearch elasticsearch 4.0K May 19 02:02 .
drwxr-xr-x 3 elasticsearch elasticsearch 4.0K May 19 01:58 ..
-rw-r--r-- 1 elasticsearch elasticsearch  14K May 19 01:58 elasticsearch-analysis-hebrew-1.7.jar
-rw-r--r-- 1 elasticsearch elasticsearch  85K May 19 01:58 hebmorph-lucene-2.0.3.jar
drwxr-xr-x 2 elasticsearch elasticsearch 4.0K May 19 02:02 hspell-data-files

/usr/share/elasticsearch/plugins/analysis-hebrew/hspell-data-files:
total 584K
drwxr-xr-x 2 elasticsearch elasticsearch 4.0K May 19 02:02 .
drwxr-xr-x 3 elasticsearch elasticsearch 4.0K May 19 02:02 ..
-rw-r--r-- 1 elasticsearch elasticsearch 2.3K May 19 02:02 dmask.c
-rw-r--r-- 1 elasticsearch elasticsearch  670 May 19 02:02 hebrew_stop.txt
-rw-r--r-- 1 elasticsearch elasticsearch  99K May 19 02:02 hebrew.wgz
-rw-r--r-- 1 elasticsearch elasticsearch  95K May 19 02:02 hebrew.wgz.desc
-rw-r--r-- 1 elasticsearch elasticsearch  39K May 19 02:02 hebrew.wgz.prefixes
-rw-r--r-- 1 elasticsearch elasticsearch   33 May 19 02:02 hebrew.wgz.sizes
-rw-r--r-- 1 elasticsearch elasticsearch 305K May 19 02:02 hebrew.wgz.stems
-rw-r--r-- 1 elasticsearch elasticsearch 7.6K May 19 02:02 prefixes.c
-rw-r--r-- 1 elasticsearch elasticsearch  856 May 19 02:02 prefix_h.gz
-rw-r--r-- 1 elasticsearch elasticsearch  577 May 19 02:02 prefix_noH.gz
-rw-r--r-- 1 elasticsearch elasticsearch  263 May 19 02:02 README
```

**Comment by nonZero** [comment]
OK. Problem found.

Instead of:

    hebrew.dict.path: /PATH/TO/HSPELL/FOLDER


it should be:

    hebrew.dict.path: /PATH/TO/HSPELL/FOLDER/

i.e.

    hebrew.dict.path: /usr/share/elasticsearch/plugins/analysis-hebrew/hspell-data-files/

**Comment by EgozyN** [comment]
Confirmed. Also note that you get a FileNotFoundException right above the line you provided (elasticsearch loading). Thanks a lot!

Both with and without / should be supported, this is fixed at hebmorph-lucene.
