### ISSUE TITLE
Hebrew analysis for Elasticsearch 2.x

### ISSUE THREAD

**Issue by orweinberger** [synhershko/elasticsearch-analysis-hebrew#17]
First, I wanted to thank you for making this great plugin.

Are you planning on releasing a new version that will work with newer ES versions?

**Comment by synhershko** [comment]
A new version has been released already, just not packaged as a plugin yet. I will release a plugin version in the next week or so.

**Comment by orweinberger** [comment]
Hey @synhershko, any updates on this?

Thanks.

**Comment by netanelgilad** [comment]
Hey @synhershko,
Would love to get this plugin updated for the current version of elastic.
I can create a PR myself, if you have any guidelines as to how to update hebmorph in this project (as I probably think that is the part that needs to be updated...).

Thanks

**Comment by odedniv** [comment]
+1

**Comment by synhershko** [comment]
Current version of ES is already supported (see the sources), I just haven't released the plugin package yet. Coming up folks :)

**Comment by odedniv** [comment]
Oh, found out how to install directly from GitHub (2.x supported version):
```bash
/usr/share/elasticsearch/bin/plugin install synhershko/elasticsearch-analysis-hebrew
```

Sorry :smile:

**Comment by odedniv** [comment]
Nevermind... fails with `ClassNotFoundException[com.code972.elasticsearch.plugins.AnalysisPlugin]`

😢

**Comment by synhershko** [comment]
Released now, see https://github.com/synhershko/elasticsearch-analysis-hebrew/commit/bd58a6a53513e2a7c35adef9958a264cc5ad13d8

**Comment by odedniv** [comment]
Oh wow just have up on trying to zip it... At the point of getting the security error.

Thanks!
