### ISSUE TITLE
ES permissions required for dictionary files

### ISSUE THREAD

**Issue by ido-ofir** [synhershko/elasticsearch-analysis-hebrew#23]
It is worth mentioning in the docs that the dictionary files should go in `/var/lib/hspell-data-files`. also this path will only exist on linux / osx. Windows users will probably need to put them elsewhere and add their path to the plugin's security policy manually.

**Comment by synhershko** [comment]
The dictionary is expected to be in the plugin's folder by default - this will work on Windows as well. I updated the readme though, thanks.

**Comment by ido-ofir** [comment]
Just sharing my thoughts here, but if the dictionary is expected to be in the plugin's directory then why not distribute the dictionary with the plugin and save the extra installation steps?
Thanks for your great work 🙏.
