### ISSUE TITLE
Doesn't work in ElasticSearch 5.x

### ISSUE THREAD

**Issue by nsantacruz** [synhershko/elasticsearch-analysis-hebrew#27]
ES 5.x requires that plugins be in an "elasticsearch" folder. Seems like a simple fix

**Comment by synhershko** [comment]
No, we need to compile and release the plugin for each ES version independently. We've done so for the commercial version and will release this to the open-source repo here soon.

**Comment by reissr** [comment]
Any news with releasing the 5 version?

**Comment by synhershko** [comment]
See my comment above

**Comment by reissr** [comment]
@synhershko thanks for your super quick reply!
I saw your comment and I don't mean to be rude, but I'm just wondering how soon is soon - weeks? months?.. :)

**Comment by synhershko** [comment]
Can't commit to a date, we have done some refactoring and it might take a while for it to land here. Worth noting commercial usage of this plugin requires a commercial license anyway.
