### ISSUE TITLE
Elastic 5.3.2 and 5.4.0 support

### ISSUE THREAD

**Issue by nomoa** [synhershko/elasticsearch-analysis-hebrew#31]
Hi,

we are currently testing this plugin on our cluster but we are in the process of upgrading to 5.3.2 and 5.4.x very soon.

Are there rough estimates of any release dates for these versions?

Thank you very much!

**Comment by synhershko** [comment]
Hi, it is already available to our commercial users, and I will be pushing it here next week or so

**Comment by Trey314159** [comment]
Any update on the open source release date? The Hebrew Wiki community is happy with the test instance I set up, and I'm eager to be able to deploy it to production!

**Comment by synhershko** [comment]
5.3.x was already released, 5.4.x was released for commercial users at this point.
