### ISSUE TITLE
Adding custom words to dictionary

### ISSUE THREAD

**Issue by arielshulman** [synhershko/elasticsearch-analysis-hebrew#36]
Is there an easy way adding custom (non standard dictionary worda) into the dictionary?
Like slang words? Or non dictionary acronyms?

**Comment by synhershko** [comment]
Yes, this is handled by the commercial edition and not available in the open-source version (which can only be used in non-commercial or AGPL3 licensed products).

**Comment by arielshulman** [comment]
Where can I find additional info about features and pricing?

**Comment by synhershko** [comment]
Please shoot us an email to itamar at bdbq co il
