### ISSUE TITLE
trying to automate installation

### ISSUE THREAD

**Issue by alonlu** [synhershko/elasticsearch-analysis-hebrew#37]
Hi, I'm trying to automate the installation of the plugin, but I'm having trouble suppressing the prompting for the file permissions.

Is there a way to supply the "yes" as a flag to:

bin/elasticsearch-plugin install

Or manage the permissions separately outside the installation process?

What's the best way to handle that?

Thanks for this great plugin!

**Comment by synhershko** [comment]
use `bin/elasticsearch-plugin install --batch`
