### ISSUE TITLE
plugin installation problem on ES 6.2.3

### ISSUE THREAD

**Issue by etombi** [synhershko/elasticsearch-analysis-hebrew#40]
Hi . im getting this error -ERROR: elasticsearch directory is missing in the plugin zip
when running the command to install the plugin.

**Comment by etombi** [comment]
Hi . im getting this error -ERROR: `elasticsearch` directory is missing in the plugin zip
when running the command to install the plugin.

**Comment by synhershko** [comment]
Hi, the plugin was released for 6.x versions only in it's commercial form. We will release the OSS flavor later this year. Please note any commercial / non-AGPL3 usage of this plugin requires acquiring a commercial license. Feel free to reach out for acquiring a commercial version compatible with 6.2.3.
