### ISSUE TITLE
Support for the new version (6.2.4) of Elasticsearch

### ISSUE THREAD

**Issue by yoelsharf** [synhershko/elasticsearch-analysis-hebrew#41]
Right now when trying to install the plug-in I get this exception:
"plugin [analysis-hebrew] is incompatible with version [6.2.4]; was designed for version [5.3.0]"

**Comment by synhershko** [comment]
We have released a 6.x compatible versions and at the moment it is only available to our commercial users.

Please note a commercial license is required for any commercial usage (unless you release your own codebase under the AGPL3). The commercial license includes a proprietary dictionary that is replacing the hspell dictionary that you are currently using and is built specifically for the search use case. Our dictionary is being maintained and updated versions of it are released periodically with new words and other improvements.

In addition in the subscription model we guarantee a plugin version for every Elasticsearch version > 2.x (including 5.x and 6.x) and Solr version > 5.x and new versions as they are being released. The commercial plugin also includes the ability to override dictionary entries (something that most customers use for better compatibility to their domain.

You are welcome to reach out on private channels to continue the discussion.
