### ISSUE TITLE
IllegalArgumentException: Could not load any dictionary. 

### ISSUE THREAD

**Issue by yoelsharf** [synhershko/elasticsearch-analysis-hebrew#42]
Installed the 5.3.0 version of HebMorph and after restart Elasticsearch, I'v got the exception
![image](https://user-images.githubusercontent.com/25791189/41662091-fc1dfd4a-74a8-11e8-93b0-a04b0828815b.png)

**Comment by synhershko** [comment]
Make sure the `hspell-data-files` (the dictionary) is placed in the correct location (there are several legal locations, the best one would be under the Hebrew analysis plugin folder). Newer versions of the plugin contain the dictionary bundled with the plugin.

**Comment by yoelsharf** [comment]
It contains under elasticsearch-5.3.0\plugins\analysis-hebrew\hspell-data-files

**Comment by synhershko** [comment]
Are you running on Windows? I think this was an error we had fixed on a more recent version. Can you try with 5.6.0? Same download URL just different version number

**Comment by yoelsharf** [comment]
Yes, I am running on Windows. The problem solved after upgrading to the 5.6.0 version.
