### ISSUE TITLE
Won't install on Elasticsearch 6.3.1

### ISSUE THREAD

**Issue by LevMuchnik** [synhershko/elasticsearch-analysis-hebrew#43]
Error message when installing on v6.3.1

> ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.

**Comment by synhershko** [comment]
We have released a 6.x compatible versions and at the moment it is only available to our commercial users.

Please note a commercial license is required for any commercial usage (unless you release your own codebase under the AGPL3). The commercial license includes a proprietary dictionary that is replacing the hspell dictionary that you are currently using and is built specifically for the search use case. Our dictionary is being maintained and updated versions of it are released periodically with new words and other improvements.

In addition in the subscription model we guarantee a plugin version for every Elasticsearch version > 2.x (including 5.x and 6.x) and Solr version > 5.x and new versions as they are being released. The commercial plugin also includes the ability to override dictionary entries (something that most customers use for better compatibility to their domain.

You are welcome to reach out on private channels to continue the discussion.
