### ISSUE TITLE
Build documentation

### ISSUE THREAD

**Issue by odedniv** [synhershko/elasticsearch-analysis-hebrew#45]
Hi, can you describe in the docs how to build this locally (and use it with a local elasticsearch), so when a new version of Elasticsearch comes people can build it themselves?

My Linux distro does not maintain any of the versions you have deployed to https://bintray.com/synhershko/elasticsearch-analysis-hebrew/elasticsearch-analysis-hebrew-plugin and I don't want to bother you with specific versions.

Thanks!

**Comment by synhershko** [comment]
Hi Oded,

The build scripts are quite easy to use (via gradle). FYI, we have released a 6.x compatible versions and at the moment it is only available to our commercial users.

Please note a commercial license is required for any commercial usage (unless you release your own codebase under the AGPL3). The commercial license includes a proprietary dictionary that is replacing the hspell dictionary that you are currently using and is built specifically for the search use case. Our dictionary is being maintained and updated versions of it are released periodically with new words and other improvements.

In addition in the subscription model we guarantee a plugin version for every Elasticsearch version > 2.x (including 5.x and 6.x) and Solr version > 5.x and new versions as they are being released. The commercial plugin also includes the ability to override dictionary entries (something that most customers use for better compatibility to their domain.

You are welcome to reach out on private channels to continue the discussion.
