### ISSUE TITLE
/_hebrew/check-word/בדיקה returns NON_HEBREW response

### ISSUE THREAD

**Issue by barakdof** [synhershko/elasticsearch-analysis-hebrew#49]
ElasticSearch version 5.2.1, "lucene_version" : "6.4.1"
Matching plugin for 5.x was installed and logs were checked and are ok.

The test:
/_hebrew/check-word/בדיקה

returns:
{"word":"ￗﾑￗﾓￗﾙￗﾧￗﾔ","wordType":"NON_HEBREW"}

Can you please help me understand how could it be that gibberish is returned?

**Comment by synhershko** [comment]
The string you entered isn't Hebrew, not sure what the question is

**Comment by barakdof** [comment]
the string is "בדיקה" (/_hebrew/check-word/בדיקה)

**Comment by synhershko** [comment]
Got it. Might be an encoding issue on your system / tools used to execute
the check. This works well for me here.
--

Itamar Syn-Hershko
CTO, Founder
BigData Boutique <http://bigdataboutique.com/>
Elasticsearch Consulting Partner
Microsoft MVP | Lucene.NET PMC
http://code972.com | @synhershko <https://twitter.com/synhershko>

**Comment by barakdof** [comment]
elasticsearch and the plugin are installed on a centos7 server.

i created the following php script (say `test.php`) and called:

`test.php?word=15HXk9eZ16fXlA==`

where: `15HXk9eZ16fXlA==` is "בדיקה" in base64.
Because it's base64 then encoding problems are not supposed to happen. Do you have any idea?

```
<?php
$word = base64_decode ($_GET['word']);
$url = "http://localhost:9200/_hebrew/check-word/$word";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$body = curl_exec($ch);
curl_close($ch);

echo $body
?>
```

**Comment by synhershko** [comment]
No , just don't pass it as base64

FYI, usage of this plugin in a production commercial environment requires a
commercial license
--

Itamar Syn-Hershko
CTO, Founder
BigData Boutique <http://bigdataboutique.com/>
Elasticsearch Consulting Partner
Microsoft MVP | Lucene.NET PMC
http://code972.com | @synhershko <https://twitter.com/synhershko>

**Comment by synhershko** [comment]
Closing as this is an encoding issue on your end, not an issue with HebMorph / hebrew-analysis-plugin
