### ISSUE TITLE
Can't install plugin on ES 7.4.0/Windows

### ISSUE THREAD

**Issue by jonyt** [synhershko/elasticsearch-analysis-hebrew#50]
This is on Windows 10 and ES 7.4.0. When I issue `elasticsearch-plugin.bat install https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip` I get:
```
-> Downloading https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip
[=================================================] 100%  
ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.
```

**Comment by synhershko** [comment]
Hello @jonyt  ,

We thank you for you interest.

We have released a 7.x compatible versions and at the moment it is only available to our commercial users.

Please note a commercial license is required for any commercial usage (unless you release your own codebase under the AGPL3). The commercial license includes a proprietary dictionary that is replacing the hspell dictionary that you are currently using and is built specifically for the search use case. Our dictionary is being maintained and updated versions of it are released periodically with new words and other improvements.

In addition in the subscription model we guarantee a plugin version for every Elasticsearch version > 2.x (including 5.x and 6.x) and Solr version > 5.x and new versions as they are being released. The commercial plugin also includes the ability to override dictionary entries (something that most customers use for better compatibility to their domain.

You are welcome to reach out on private channels to continue the discussion.

**Comment by zamankul74** [comment]
How I can install your plugin on locally installed ubuntu 18.04 for testing?
I readme file I can't see any linux based instructions

**Comment by synhershko** [comment]
@zamankul74 the plugin is OS independent, it just needs to be installed on an ES instance. Please read my comment above regarding support for this plugin.
