### ISSUE TITLE
Jfrog zip is deprecated, can't install zipped plugin

### ISSUE THREAD

**Issue by AvivBenShoham** [synhershko/elasticsearch-analysis-hebrew#55]
![image](https://user-images.githubusercontent.com/46964264/147411381-d4f2895c-c4a5-4b8f-ad9d-bc49f2d7e10a.png)

**Comment by synhershko** [comment]
Hi @dor6-jul


We thank you for you interest.

We have released a 7.x compatible versions and at the moment it is only available to our commercial users.

Please note a commercial license is required for any commercial usage (unless you release your own codebase under the AGPL3). The commercial license includes a proprietary dictionary that is replacing the hspell dictionary that you are currently using and is built specifically for the search use case. Our dictionary is being maintained and updated versions of it are released periodically with new words and other improvements.

In addition in the subscription model we guarantee a plugin version for every Elasticsearch version > 2.x (including 7.x of course) and Solr version > 5.x and new versions as they are being released. The commercial plugin also includes the ability to override dictionary entries (something that most customers use for better compatibility to their domain.

You are welcome to reach out on private channels to continue the discussion.

**Comment by synhershko** [comment]
Hi @AvivBenShoham ,

We thank you for you interest.

We have recent versions released and at the moment it is only available to our commercial users.

Please note a commercial license is required for any commercial usage (unless you release your own codebase under the AGPL3). The commercial license includes a proprietary dictionary that is replacing the hspell dictionary that you are currently using and is built specifically for the search use case. Our dictionary is being maintained and updated versions of it are released periodically with new words and other improvements.

In addition in the subscription model we guarantee a plugin version for every Elasticsearch version > 2.x (including 7.x of course) and Solr version > 5.x and new versions as they are being released. The commercial plugin also includes the ability to override dictionary entries (something that most customers use for better compatibility to their domain.

You are welcome to reach out on private channels to continue the discussion, or reach out at https://ey.fo/he/contact
