### ISSUE TITLE
The plugin download link is not valid

### ISSUE THREAD

**Issue by asaf050** [synhershko/elasticsearch-analysis-hebrew#56]
The download link describe in the README doesn't work
https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip

**Comment by synhershko** [comment]
We thank you for you interest.

We have recent versions released and at the moment it is only available to our commercial users.

Please note a commercial license is required for any commercial usage (unless you release your own codebase under the AGPL3). The commercial license includes a proprietary dictionary that is replacing the hspell dictionary that you are currently using and is built specifically for the search use case. Our dictionary is being maintained and updated versions of it are released periodically with new words and other improvements.

In addition in the subscription model we guarantee a plugin version for every Elasticsearch version > 2.x (including 7.x of course) and Solr version > 5.x and new versions as they are being released. The commercial plugin also includes the ability to override dictionary entries (something that most customers use for better compatibility to their domain.

You are welcome to reach out on private channels to continue the discussion, or reach out at https://ey.fo/he/contact

**Comment by asaf050** [comment]
Thanks for the quick reply.
So if my codebase is based on AGPL3, how can I download the plugin?
