### ISSUE TITLE
Missing resource for hebrew analyser

### ISSUE THREAD

**Issue by stephaniejacq** [synhershko/elasticsearch-analysis-hebrew#57]
Hello,

the site hosting the zip archives of the plugin versions, seems to have changed. The url 'https://bintray.com/synhershko/elasticsearch-analysis-hebrew/download_file?file_path=elasticsearch-analysis-hebrew-5.3.0.zip' redirect to another website.
Is there another repository to download them?

Thanks

**Comment by synhershko** [comment]
We thank you for you interest.

We have recent versions released and at they are only available to our commercial users. This also holds true for older versions which were previously public on bintray which is now closed.

Please note a commercial license is required for any commercial usage (unless you release your own codebase under the AGPL3). The commercial license includes a proprietary dictionary that is replacing the hspell dictionary that you are currently using and is built specifically for the search use case. Our dictionary is being maintained and updated versions of it are released periodically with new words and other improvements.

In addition in the subscription model we guarantee a plugin version for every Elasticsearch version > 2.x (including 7.x of course) and Solr version > 5.x and new versions as they are being released. The commercial plugin also includes the ability to override dictionary entries (something that most customers use for better compatibility to their domain.

You are welcome to reach out on private channels to continue the discussion, or reach out at https://ey.fo/he/contact
