### ISSUE TITLE
Lucene 4.10 / ElasticSearch 1.4

### ISSUE THREAD

**Issue by EliezerIsrael** [synhershko/elasticsearch-analysis-hebrew#7]
Any plan to package and release the new Lucene 4.10 / ElasticSearch 1.4 support in HebMorph?

**Comment by synhershko** [comment]
Yes, it is already in the works

**Comment by EliezerIsrael** [comment]
I've seen activity in this direction, but it's not clear to me if it's packaged.  What's status?

**Comment by synhershko** [comment]
HebMorph 2.0.x supports Lucene 4.10 , we are working on releasing an updated Elasticsearch plugin, the delay is due to some compatibility issues with the commercial version

**Comment by synhershko** [comment]
This is now released, version 1.6 is compatible with ES 1.4.x and 1.5.x

**Comment by EliezerIsrael** [comment]
:+1:

**Comment by EliezerIsrael** [comment]
I don't see 1.6 available in the bintray...
How should we install?

**Comment by synhershko** [comment]
See the updated readme
